[package]
name = "leetcode_solvers"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
log4rs = "1.3.0"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1"
serde_derive = "1.0.205"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
